quarkus:
  rest-client:
    logging:
      scope: request-response
      body-limit: 1024
    boavizta-api-url:
      uri: "https://api.boavizta.org/v1/"
  log:
    category:
      "persistence":
        min-level: TRACE
        level: TRACE
  datasource:
    db-kind: sqlite
    jdbc:
      url: "jdbc:sqlite:data/db/local.db"
      min-size: 0
  hibernate-orm:
    schema-management:
      strategy: none
  flyway:
    migrate-at-start: false
    locations: classpath:db/migration

monitor:
  cron: "*/10 * * * * ?" # every 10s

persistence:
  enable-memory-target: true

backup:
  enabled: false
  cron: "0 0 2 * * ?"

profiles:
  seeds:
    - id: "aws-c5a-16xlarge"
      description: "AWS c5a.16xlarge FRA"
      provider: aws
      instance-type: "c5a.16xlarge"
      location: "FRA"
      lifespan: 43800
    - id: "aws-c5a-4xlarge"
      description: "AWS c5a.4xlarge FRA"
      provider: aws
      instance-type: "c5a.4xlarge"
      location: "FRA"
      lifespan: 43800
    - id: "gcp-n2-highcpu-32"
      description: "GCP n2-highcpu-32 FRA"
      provider: gcp
      instance-type: "n2-highcpu-32"
      location: "FRA"
      lifespan: 43800
  default: "aws-c5a-4xlarge"
