quarkus:
  rest-client:
    logging:
      scope: request-response
      body-limit: 1024
    boavizta-api-url:
      uri: "https://api.boavizta.org/v1/"
    prometheus-api-url:
      uri: "http://localhost:9090/api/v1"
  log:
    category:
      "persistence":
        min-level: TRACE
        level: TRACE
  datasource:
    db-kind: sqlite
    jdbc:
      url: "jdbc:sqlite:data/db/local.db"
      min-size: 0
  hibernate-orm:
    database:
      generation: none

monitor:
  cron: "*/10 * * * * ?" # every 10s
  kubernetes-configs:
    geocheck:
      namespace: "geocheck"

persistence:
  enable-memory-target: true
  enable-meter-target: true

profile:
  server:
    enable: true
    provider: aws
    instance-type: "c5a.16xlarge"
    location: "FRA"
    lifespan: 43800 #5 years
